---
# tasks file for httpd
- name: install apache
  dnf:
          name: httpd
          state: present
  become: true        
- name: Start and enable the service
  service:
          name: httpd
          state: started
          enabled: yes
